# Generated by Django 5.1.2 on 2024-10-16 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Le nom ne doit contenir que des lettres.')])),
                ('prenom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Le prénom ne doit contenir que des lettres.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^07\\d{8}$', "Le contact doit être un numéro valide de Côte d'Ivoire commençant par 07.")])),
                ('alumni', models.BooleanField(default=False)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], max_length=2)),
                ('mot_de_passe', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
