# Generated by Django 5.1.2 on 2024-10-17 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_twin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^07\\d{8}$', "le numero n'est pas valide")]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Le prénom ne doit contenir que des lettres.')]),
        ),
    ]
